# Generated by Django 3.1.7 on 2021-05-10 21:47

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombres del usuario')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos del usuario')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='correo del usuario')),
                ('contact_email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='correo del padre de familia')),
                ('date_of_birth', models.DateField(verbose_name='fecha de nacimiento')),
                ('photo', models.ImageField(blank=True, upload_to='users/pictures')),
                ('username', models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre de usuario.'}, help_text='Su usuario debe tener maximo 60 caracteres. Letras, dígitos y @/./+/-/_ solamente.', max_length=60, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='usuario')),
                ('type_user', models.CharField(choices=[('ADMIN', 'Administrador'), ('STDT', 'Estudiante'), ('IVT', 'Invitado')], default='STDT', max_length=8, verbose_name='tipo de usuario')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que la cuenta del usuario está activa.', verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa si este usuario puede acceder al sitio de administración.', verbose_name='login en admin')),
                ('terms', models.BooleanField(verbose_name='terminos y condiciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación de la cuenta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.AutoField(primary_key=True, serialize=False)),
                ('code_department', models.IntegerField(verbose_name='codigo departamento')),
                ('code_municipality', models.IntegerField(verbose_name='codigo municipio')),
                ('name_department', models.CharField(max_length=60, verbose_name='nombre departamento')),
                ('name_municipality', models.CharField(max_length=60, verbose_name='nombre municipio')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='nombre del reporte')),
                ('type', models.CharField(max_length=60, verbose_name='tipo de reporte')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'db_table': 'report',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location'),
        ),
    ]
