# Generated by Django 4.1 on 2022-09-07 23:18

import apps.contents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción de la publicación')),
                ('image', models.ImageField(upload_to=apps.contents.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagen de la publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del autor del contenido')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(verbose_name='Me gusta')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='like')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gustas',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.contents.models.upload_to_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf', 'pptx'])], verbose_name='archivo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='enlace del documento')),
                ('file_type', models.CharField(choices=[('PDF', 'Archivo PDF'), ('WORD', 'Archivo WORD'), ('POWER_POINT', 'Archivo POWER POINT'), ('URL', 'Enlace del archivo')], max_length=11, verbose_name='tipo de archivo')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contents.content', verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'documento extra por publicación',
                'verbose_name_plural': 'documentos extra por publicación',
                'db_table': 'document_content',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Nombre de usuario')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'comment',
            },
        ),
    ]
