INSERT INTO school(school_id, school_name ,location_id, photo)
VALUES(1,'No tengo colegio',7, '' ),
(2,'Colegio de Boyacá',7, 'school/ESCUDO COLBOY.png' ),
(3,'Escuela normal superior Santiago de Tunja ',7 ,''),
(4,'Instituto de Educación media diversificada Inem Carlos Arturo torres ' ,7,'' ),
(5,'Institución educativa san Jerónimo Emiliani ' ,7,'' ),
(6,'I.e. Silvino Rodríguez ' ,7,'' ),
(7,'Institución educativa Antonio José Sandoval Gómez de Tunja ' ,7,'' ),
(8,'Escuela normal superior Leonor Álvarez Pinzón ' ,7 ,''),
(9,'Colegio andino de Tunja ' ,7 ,''),
(10,'Colegio salesiano Maldonado ' ,7 ,''),
(11,'Gustavo rojas pinilla ' ,7 ,''),
(12,'Colegio nuestra señora del rosario ' ,7 ,''),
(13,'Colegio cristiano filadelfia ' ,7 ,''),
(14,'Centro educativo san Agustín ' ,7 ,''),
(15,'Col Coop Cooservicios ' ,7 ,''),
(16,'Inst Educ libertador Simón Bolívar ' ,7 ,''),
(17,'Colegio mi pequeño mundo ' ,7 ,''),
(18,'Colegio cristo rey ' ,7 ,''),
(19,'Colegio Corporación santo domingo ' ,7 ,''),
(20,'Gimnasio villa fontana ' ,7 ,''),
(21,'Instituto Técnico Gonzalo Suarez Rendón ' ,7 ,''),
(22,'Colegio los ángeles ' ,7,'' ),
(23,'Centro juvenil Amigoniano Boyacá ' ,7 ,''),
(24,'Institución educativa rural del sur ' ,7 ,'');
