INSERT INTO school(school_id,school_name ,location_id_id )
VALUES (1,'Colegio de Boyacá',7 ),
(2,'Escuela normal superior Santiago de Tunja ',7 ),
(3,'Instituto de Educación media diversificada Inem Carlos Arturo torres ' ,7 ),
(4,'Institución educativa san Jerónimo Emiliani ' ,7 ),
(5,'I.e. Silvino Rodríguez ' ,7 ),
(6,'Institución educativa Antonio José Sandoval Gómez de Tunja ' ,7 ),
(7,'Escuela normal superior Leonor Álvarez Pinzón ' ,7 ),
(8,'Colegio andino de Tunja ' ,7 ),
(9,'Colegio salesiano Maldonado ' ,7 ),
(10,'Gustavo rojas pinilla ' ,7 ),
(11,'Colegio nuestra señora del rosario ' ,7 ),
(12,'Colegio cristiano filadelfia ' ,7 ),
(13,'Centro educativo san Agustín ' ,7 ),
(14,'Col Coop Cooservicios ' ,7 ),
(15,'Inst Educ libertador Simón Bolívar ' ,7 ),
(16,'Colegio mi pequeño mundo ' ,7 ),
(17,'Colegio cristo rey ' ,7 ),
(18,'Colegio Corporación santo domingo ' ,7 ),
(19,'Gimnasio villa fontana ' ,7 ),
(20,'Instituto Técnico Gonzalo Suarez Rendón ' ,7 ),
(21,'Colegio los ángeles ' ,7 ),
(22,'Centro juvenil Amigoniano Boyacá ' ,7 ),
(23,'Institución educativa rural del sur ' ,7 );
