# Generated by Django 3.2.9 on 2021-11-30 14:43

import apps.schools.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción de la publicación')),
                ('image', models.ImageField(upload_to=apps.schools.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagen de la publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=120, verbose_name='nombre del colegio')),
                ('photo', models.ImageField(upload_to=apps.schools.models.upload_to_school, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Logo o escudo de un colegio')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location', verbose_name='ubicación')),
            ],
            options={
                'verbose_name': 'colegio',
                'verbose_name_plural': 'colegios',
                'db_table': 'school',
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(verbose_name='Me gusta')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='like')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gustas',
                'db_table': 'like',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Nombre del Colegio'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Nombre de usuario')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'comment',
            },
        ),
    ]
