# Generated by Django 3.1.7 on 2021-05-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=50, verbose_name='nombre categoria')),
                ('description', models.CharField(max_length=60, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id_school', models.AutoField(primary_key=True, serialize=False)),
                ('code_dane', models.CharField(max_length=30, verbose_name='codigo dane del colegio')),
                ('name_school', models.CharField(max_length=120, verbose_name='nombre del colegio')),
                ('name_calendar', models.CharField(max_length=20, null=True, verbose_name='tipo calendario')),
                ('address', models.CharField(max_length=120, null=True, verbose_name='dirección del colegio')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
            options={
                'verbose_name': 'colegio',
                'verbose_name_plural': 'colegios',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('name_content', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción de la publicación')),
                ('image', models.ImageField(blank=True, upload_to='content/image', verbose_name='Imagen de la publicación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.category')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'db_table': 'content',
            },
        ),
    ]
