# Generated by Django 3.1.7 on 2021-05-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=120, verbose_name='nombre del colegio')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'colegio',
                'verbose_name_plural': 'colegios',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('description', models.CharField(max_length=60, verbose_name='Descripción de la publicación')),
                ('image', models.ImageField(upload_to='content/image', verbose_name='Imagen de la publicación')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenidos',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, verbose_name='comentario')),
                ('like', models.BooleanField(verbose_name='Me gusta')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.content')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'db_table': 'comment',
            },
        ),
    ]
