# Generated by Django 4.1 on 2022-09-05 22:07

import apps.schools.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.schools.models.upload_to_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf', 'pptx'])], verbose_name='archivo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='enlace del documento')),
                ('file_type', models.CharField(choices=[('PDF', 'Archivo PDF'), ('WORD', 'Archivo WORD'), ('POWER_POINT', 'Archivo POWER POINT'), ('URL', 'Enlace del archivo')], max_length=11, verbose_name='tipo de archivo')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.content', verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'documento extra por publicación',
                'verbose_name_plural': 'documentos extra por publicación',
                'db_table': 'document_content',
            },
        ),
    ]
