# Generated by Django 4.1 on 2022-09-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_documentcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schools.content', verbose_name='contenido'),
        ),
    ]
