"""
Django settings for webchatbot project.

Generated by 'django-admin startproject' using Django 3.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path

from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',

    # apps local
    'apps.accounts',
    'apps.schools',
    'apps.contents',

    # django rest framework
    'rest_framework',
    'rest_framework.authtoken',

    # django cleanup
    'django_cleanup',
]
X_FRAME_OPTIONS = 'SAMEORIGIN'  # only if django version >= 3.0

# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'accounts.User'

# Django-allauth
SITE_ID = 1
# email requerido
ACCOUNT_EMAIL_REQUIRED = True
# se pueda deslogear
ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 2  # Limite de intentos para iniciar sesion

ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Verifica que se loguee con email
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'Chatbot - '

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECRET_KEY_TOKEN = config('SECRET_KEY_TOKEN')
JWT_ACTIVATION_ACCOUNT_EXPIRE_DELTA = timedelta(
    days=1)  # Numero de días para que expire el email de verificacion de cuenta
JWT_RESET_PASSWORD_EXPIRE_DELTA = timedelta(minutes=15)
JWT_CHANGE_EMAIL_CONFIRMATION_EXPIRE_DELTA = timedelta(minutes=15)

ACCOUNT_FORMS = {
    # 'login': 'apps.accounts.forms.CustomLoginForm',
    'signup': 'apps.accounts.forms.SignupForm',
    'reset_password': 'apps.accounts.forms.CustomResetPasswordForm',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'webchatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.AllowAllUsersModelBackend',

]

WSGI_APPLICATION = 'webchatbot.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = "/static/"


CORS_ALLOWED_ORIGINS = [
    "http://localhost:9016",
    "https://chatcomp.netlify.app",
    "place-study.web.app",
    "place-study.firebaseapp.com"
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# Admin
ADMIN_URL = config('DJANGO_ADMIN_URL')

WHITENOISE_AUTOREFRESH = True

# Email settings
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # env
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')  # env
# Default admin email
DEFAULT_ADMIN_EMAIL = config('DEFAULT_ADMIN_EMAIL')  # env
